services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=atlas
    command: --http-api-update --cleanup --http-api-periodic-polls
    expose:
      - 8080
    privileged: true

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    expose:
      - 2333
    ports:
      - 2333:2333
    environment:
      - _JAVA_OPTIONS=-Xmx4G
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins/:/opt/Lavalink/plugins/

  atlas:
    image: ghcr.io/tygrxqt/atlas:latest
    container_name: atlas
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=
      - PREFIX=>
      - SPOTIFY_CLIENT_ID=
      - SPOTIFY_CLIENT_SECRET=
      - LAVALINK_NAME=localhost
      - LAVALINK_HOST=lavalink
      - LAVALINK_PORT=2333
      - LAVALINK_PASSWORD=youshallnotpass
      - LAVALINK_SECURE=false
    depends_on:
      - lavalink
      - watchtower